language: julia
os:
  - linux
julia:
  - 1.0
  - 1.1
  - nightly


# before_install:
#   - sudo apt-get -qq update
#   - sudo apt-get install -y hdf5-tools python-numpy python-scipy python-matplotlib
#   - julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/crstnbr/StableDQMC.jl.git"))'

addons:
  apt:
    packages:
      - python-numpy
      - python-scipy
      - python-matplotlib
      - hdf5-tools

notifications:
  email: false

matrix:
  allow_failures:
    - julia: nightly

# code coverage
after_success:
  # push coverage results to Codecov
  - julia -e 'using Pkg; cd(Pkg.dir("MonteCarlo")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  # push coverage results to Coveralls
  - julia -e 'using Pkg; cd(Pkg.dir("MonteCarlo")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # Documenter
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("MonteCarlo")); include(joinpath("docs", "make.jl"))'
