name: Run tests

on:
  push:
    paths-ignore:
    - 'README.md'
  pull_request:
    paths-ignore:
    - 'README.md'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        julia-version: [1]
        julia-arch: [x64]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    env:
      MONTECARLO_USE_LOOPVECTORIZATION: false

    steps:
      - uses: actions/checkout@v1.0.0
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-buildpkg@master
      - uses: julia-actions/julia-runtest@master
      - uses: julia-actions/julia-uploadcodecov@master
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
#      - uses: julia-actions/julia-uploadcoveralls@latest
#        env:
#          COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
